import AddVideo from "./components/AddVideo";
import UpdateVideo from "./components/UpdateVideo";
import AdminLogin from "./pages/Dashboard/AdminLogin";
import Assignments from "./pages/Dashboard/Assignments";
import AssignmentsMark from "./pages/Dashboard/AssignmentsMark";
import DashBoard from "./pages/Dashboard/DashBoard";
import Quizzes from "./pages/Dashboard/Quizzes";
import Videos from "./pages/Dashboard/Videos";
import CoursePlayer from "./pages/StudentPortal/CoursePlayer";
import LeaderBorad from "./pages/StudentPortal/LeaderBorad";
import Quiz from "./pages/StudentPortal/Quiz";
import StudentLogin from "./pages/StudentPortal/StudentLogin";
import StudentRegistration from "./pages/StudentPortal/StudentRegistration";
export {CoursePlayer,LeaderBorad,Quiz,StudentLogin,StudentRegistration,AdminLogin,Assignments,AssignmentsMark,DashBoard,Quizzes,Videos,AddVideo,UpdateVideo};